//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Cimetrix.EDAConnect.E134-0707")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="Cimetrix.EDAConnect.E134-0707", IsNullable=false)]
public partial class DCP {
    
    private string descriptionField;
    
    private DCPEvent[] eventField;
    
    private string idField;
    
    private string nameField;
    
    private string persistentField;
    
    private string intervalField;
    
    private string definedField;
    
    private string definedByField;
    
    private string timeDefinedField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Event")]
    public DCPEvent[] Event {
        get {
            return this.eventField;
        }
        set {
            this.eventField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Persistent {
        get {
            return this.persistentField;
        }
        set {
            this.persistentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Interval {
        get {
            return this.intervalField;
        }
        set {
            this.intervalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Defined {
        get {
            return this.definedField;
        }
        set {
            this.definedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DefinedBy {
        get {
            return this.definedByField;
        }
        set {
            this.definedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TimeDefined {
        get {
            return this.timeDefinedField;
        }
        set {
            this.timeDefinedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Cimetrix.EDAConnect.E134-0707")]
public partial class DCPEvent {
    
    private DCPEventParametersParameter[][] parametersField;
    
    private string idField;
    
    private string sourceIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", typeof(DCPEventParametersParameter), IsNullable=false)]
    public DCPEventParametersParameter[][] Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceId {
        get {
            return this.sourceIdField;
        }
        set {
            this.sourceIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Cimetrix.EDAConnect.E134-0707")]
public partial class DCPEventParametersParameter {
    
    private string nameField;
    
    private string sourceIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceId {
        get {
            return this.sourceIdField;
        }
        set {
            this.sourceIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Cimetrix.EDAConnect.E134-0707")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="Cimetrix.EDAConnect.E134-0707", IsNullable=false)]
public partial class NewDataSet {
    
    private DCP[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DCP")]
    public DCP[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
